### ISSUE TITLE
Ramifications of running this every 30 seconds?

### ISSUE THREAD

**Issue by Ph0rkoz** [georgewhewell/undervolt#86] opened 2019-10-24 23:41 UTC
Do we really want undervolt to run every 30 seconds? Would this not produce wakeups, etc?

Is there a better length of time to re-set the undervolt?

**Comment by Ph0rkoz** [comment] 2019-10-27 17:16
Ok, found one ramification.... undervolt spams the hell out of the logs.

**Comment by retromuz** [comment] 2019-10-29 07:08
That's true about the logs.
However, my idle consumption stays well below 10W (~ 6 - 7). Sometimes it even goes down to ~ 4 - 5 Watts. I comfortably got more than 10 hours of battery life. Time to time I run ~2 virtual machines under VirtualBox. Do remote desktop via Remmina all the time. Still get at least 8 hours of battery. This is pretty good for me.

**Comment by Ph0rkoz** [comment] 2019-10-31 01:07
Yes, undervolting itself = good. Spamming my logs = killing my ssd.

**Comment by georgewhewell** [comment] 2019-11-01 21:10
dupe of #45 

if you don't want any output then drop the `-v` flag from your service

**Closed as completed by georgewhewell** 2019-11-01 21:10 UTC

**Comment by Ph0rkoz** [comment] 2019-11-03 12:47
Thank you. It really is that easy. Please mention it in the docs since it wasn't as obvious as it should have been.
